ASP.NETCoreInClass/MyBlog/MyBlog/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using MyBlog.Interfaces;
using MyBlog.Models;
using MyBlog.ViewModel;

namespace MyBlog.Controllers
{
    public class AdminController : Controller
    {

        private IPostRepository _postRep;
        private IHostingEnvironment hostingEnvironment;
        public AdminController(IPostRepository postRep, IHostingEnvironment hostingEnvironment)
        {
            _postRep = postRep;
            this.hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Admin()
        {
            return View();
        }
        public IActionResult PostEditor(int postID)
        {
            return View();
        }

        [HttpGet]
        public ViewResult CreatePost()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreatePost(PostCreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                string uniqFileName = null;
                if (model.img != null)
                {
                    string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                    uniqFileName = Guid.NewGuid().ToString() + "_" + model.img.FileName;
                    string filePath = Path.Combine(uploadsFolder, uniqFileName);
                    model.img.CopyTo(new FileStream(filePath, FileMode.Create));
                }
                else
                {
                    uniqFileName = "no.png";
                }
                BlogModel newPost = new BlogModel
                {
                    author = model.author,
                    title = model.title,
                    preview = model.preview,
                    fullPost = model.fullPost,
                    img = uniqFileName
                };
                _postRep.CreatePost(newPost);

                return RedirectToRoute("default", new { controller = "Blog", action = "Index" });

            }
            return View();

        }
    }
}

ASP.NETCoreInClass/MyBlog/MyBlog/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyBlog.Models;
using MyBlog.ViewModel;

namespace MyBlog.Controllers
{
   // [Authorize(Roles = "Admin")]
    public class AdministratorController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<AppUser> userManager;

        public AdministratorController(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult CreateRole()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole
                {
                    Name = model.RoleName
                };

                IdentityResult result = await roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Blog");
                }

                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult ListRoles()
        {
            var roles = roleManager.Roles;
            return View(roles);
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            var role = await roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }

            var model = new EditRoleViewModel
            {
                Id = role.Id,
                RoleName = role.Name
            };

            foreach (var user in userManager.Users)
            {

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            var role = await roleManager.FindByIdAsync(model.Id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {model.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                role.Name = model.RoleName;

                var result = await roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

                return View(model);
            }
        }
        //public IActionResult Delete(string id)
        //{
        //    //var role = AppDb.Roles.Where(d => d.Name == "my role name").FirstOrDefault();
        //    //AppDb.Roles.Remove(role);
        //    //AppDb.SaveChanges();

        //    var role = roleManager.FindByIdAsync(id);
        //    if(role != null)
        //    {
        //        roleManager.Delete(role);
        //    }
        //    return RedirectToAction("Index, Blog");
        //}

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await roleManager.DeleteAsync(role);
                if (result.Succeeded)
                    return RedirectToAction("Index, Blog");
            }
            else
                ModelState.AddModelError("", "No role found");
            return View("Index", roleManager.Roles);
        }

        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleId)
        {
            ViewBag.roleId = roleId;

            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            var model = new List<UserRoleViewModel>();

            foreach (var user in userManager.Users)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;
                }

                model.Add(userRoleViewModel);
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUsersInRole(List<UserRoleViewModel> model, string roleId)
        {
            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("NotFound");
            }

            for (int i = 0; i < model.Count; i++)
            {
                var user = await userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result = null;

                if (model[i].IsSelected && !(await userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!model[i].IsSelected && await userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))
                        continue;
                    else
                        return RedirectToAction("EditRole", new { Id = roleId });
                }
            }

            return RedirectToAction("EditRole", new { Id = roleId });
        }
    }
}

ASP.NETCoreInClass/MyBlog/MyBlog/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyBlog.Entityes;
using MyBlog.Interfaces;
using MyBlog.Models;
using MyBlog.ViewModel;

namespace MyBlog.Controllers
{
    public class BlogController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly ILogger logger;

        public BlogController(DBContext context, IPostRepository postRepository,
             IHostingEnvironment hostingEnvironment,
             ILogger<BlogController> logger)
        {
            _postRepository = postRepository;
            this.hostingEnvironment = hostingEnvironment;
            this.logger = logger;
        }

        [Route("Blog/Post/{id}")]
        [AllowAnonymous]
        public IActionResult Post(int id)
        {
            logger.LogTrace("Trace Log");
            logger.LogDebug("Debug Log");
            logger.LogInformation("Information Log");
            logger.LogWarning("Warning Log");
            logger.LogError("Error Log");
            logger.LogCritical("Critical Log");
            //var query = _context.Blog.AsQueryable();

            //var posts = query.Where(post => post.id == id).Select(p => new BlogModel
            //{
            //    id = p.id,
            //    title = p.title,
            //    author = p.author,
            //    fullPost = p.fullPost,
            //    img = p.img,
            //}).SingleOrDefault();
            var post = _postRepository.GetPostById(id);
            if (post == null)
            {
                Response.StatusCode = 404;
                return View("PostNotFound", id);
            }
            return View(post);
        }

    
        public IActionResult Delete(int id)
        {
            var post = _postRepository.GetPostById(id);
            if (post.img != null && post.img != "no.png")
            {
                //видаляємо фото з папки wwwroot по заданому шляху
                string filePath = Path.Combine(hostingEnvironment.WebRootPath, "images", post.img);
                System.IO.File.Delete(filePath);
            }
            //видаляємо дані з бази по id
            _postRepository.DeletePost(id);
            //редірект на Блог
            return RedirectToAction("Index");

        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var posts = _postRepository.GetAllPosts().ToList(); 
            return View(posts);
        }
       

        [HttpGet]
        public ViewResult Edit(int id)
        {
            BlogModel post = _postRepository.GetPostById(id);
            PostEditViewModel postEditViewModel = new PostEditViewModel
            {
                Id = post.id,
                title = post.title,
                author = post.author,
                preview = post.preview,
                fullPost = post.fullPost,
                ExistImgPath = post.img
            };
            return View(postEditViewModel);
        }

        [HttpPost]
        public IActionResult Edit(PostEditViewModel model)
        {

            if (ModelState.IsValid)
            {
                BlogModel post = _postRepository.GetPostById(model.Id);
                post.author = model.author;
                post.title = model.title;
                post.preview = model.preview;
                post.fullPost = model.fullPost;

                if (model.img != null)
                {
                    if (model.ExistImgPath != null)
                    {
                        string filePath = Path.Combine(hostingEnvironment.WebRootPath, "images", model.ExistImgPath);
                        System.IO.File.Delete(filePath);
                    }
                    post.img = UploadedFile(model);
                }

                _postRepository.UpdatePost(post);
                return RedirectToAction("Index");
            }
            return View();
        }
        private string UploadedFile(PostEditViewModel model)
        {
            string uniqFileName = null;
            if (model.img != null)
            {
                string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, "images");
                uniqFileName = Guid.NewGuid().ToString() + "_" + model.img.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.img.CopyTo(fileStream);
                }
            }

            return uniqFileName;
        }

        ////[Route("Blog/Delete/{id}")]
        //public IActionResult DeleteRep()
        //{
        //    return View();
        //}
    }
}

ASP.NETCoreInClass/MyBlog/MyBlog/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
}

<h2>@ViewBag.ErrorMessage;</h2>


<a asp-controller="Blog" asp-action="Index" class="btn btn-success">Blog</a>

ASP.NETCoreInClass/MyBlog/MyBlog/Views/Shared/PostNotfound.cshtml
@model int
@{
    ViewData["Title"] = "NotFound";
}

<div class="alert alert-danger mt-1 mb-1">
    <div>404 Not Found</div>
    <h3>Post @Model not found</h3>
</div>
<a asp-action="Blog" asp-controller="Index">Post list</a>

ASP.NETCoreInClass/MyBlog/MyBlog/Views/Shared/_Layout.cshtml
@*@inject SignInManager<IdentityUser> SignInManager*@
@inject SignInManager<AppUser> SignInManager

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyBlog</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <environment include="Development">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Tripod Blog Post - Free CSS Templates</title>
        <meta name="keywords" content="free css templates, tripod, blog, full post, article page" />
        <meta name="description" content="Tripod Blog Post - free blog theme provided by templatemo.com" />
        <link href="~/css/templatemo_style.css" rel="stylesheet" type="text/css" />
        <link href="~/css_pirobox/white/style.css" media="screen" title="shadow" rel="stylesheet" type="text/css" />
        <link href="~/css/site.css" rel="stylesheet" type="text/css" />
    </environment>

    <environment include="Production">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Production">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <environment include="Production">
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title>Tripod Blog Post - Free CSS Templates</title>
        <meta name="keywords" content="free css templates, tripod, blog, full post, article page" />
        <meta name="description" content="Tripod Blog Post - free blog theme provided by templatemo.com" />
        <link href="~/css/templatemo_style.css" rel="stylesheet" type="text/css" />
        <link href="~/css_pirobox/white/style.css" media="screen" title="shadow" rel="stylesheet" type="text/css" />
        <link href="~/css/site.css" rel="stylesheet" type="text/css" />
    </environment>
</head>
<body>
    @*<div class="preloader">
            <div class="rounder">

            </div>
        </div>*@
    <header>

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Home_Page">MyBlog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Home_Page">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Portfolio">Portfolio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Services">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Index">Blog post</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Moderator"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Admin">Create Post</a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Administrator" asp-action="CreateRole">Create Role</a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Administrator" asp-action="ListRoles">List Roles</a>
                            </li>
                        }
                            @if (SignInManager.IsSignedIn(User))
                            {
                                <li class="nav-item">
                                    <form method="post" asp-controller="Account" asp-action="logout">
                                        <button type="submit" style="width:auto"
                                                class="nav-link btn btn-link py-0">
                                            Logout @User.Identity.Name
                                        </button>
                                    </form>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                                </li>
                            }
                        </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MyBlog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/piroBox.1_2_min.js" asp-append-version="true"></script>
    <script src="~/js/piroBox.1_2.js" asp-append-version="true"></script>
    <script src="~/js/jquery.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>